### ISSUE TITLE
Validating that the file is a Dexios-encrypted file

### ISSUE THREAD

**Issue by brxken128** [Antidote1911/dexiosgui#1]
In your README, you mention that Dexios-Core should add a 4-byte "magic number" to identify files that were encrypted.

I think this is a good idea, although it can still produce collisions and isn't foolproof.

I'd like to suggest implementing what I have done in the Dexios header functions (strip, dump and restore), which is attempting to deserialize the header. If the header doesn't deserialize, you can assume that it isn't valid (and if the header deserializes, but the file can't be decrypted, you can assume that the header was tampered with in some way, or that the key was incorrect). I agree that two bytes is too short, which is why I made this change.

See [here for an example](https://github.com/brxken128/dexios/blob/047c3c90c3a0011f8ea86114cf9e2ed168b51f5b/src/subcommands/header.rs#L26-L39).

**Comment by Antidote1911** [comment]
Plop brxken128 !
The main problem  is for the operating system. Most of Unix like OS identify a file with this [magic number](https://en.wikipedia.org/wiki/File_format#Magic_number) to open the good app. Some commands can use it like [file](https://en.wikipedia.org/wiki/File_(command)).
It's not possible or realist for another application to test if the header can be de-serialized to find all Dexios files (for example).
Yes, 4 bytes is not foolproof, but much much more than 2 bytes ! this why most of magic number have 4 bytes or more:
https://en.wikipedia.org/wiki/List_of_file_signatures
https://www.geeksforgeeks.org/working-with-magic-numbers-in-linux/

There is no Dexios files on my server, but 8201 are false identified as Dexios for [0xDE] presence,  
for [0xDE, 0x01] -> 32
for [0xDE, 0x02] -> 538
for [0xDE, 0x03] -> 12
for [0xDE, 0xXX] -> 8201

With a modified header with the magic:
44 45 58 49 4F 53 (DEXIOS in ASCII/unicode) -> 0
44 45 58 49 (DEXI in ASCII/unicode) -> 0

It's not a big issue, but it's interesting to introduce this constant in a future major release.

Sorry my friend, but i do not have a lot of time for 2 week. You have make a good work with Dexios-core !
